### ISSUE TITLE
Pricing Section Components for Library

### ISSUE THREAD

**Issue by syedtalaljilani** [syedtalaljilani/Water-UI#23]
- [ ]  Create a Design in Figma
- [ ]  Convert the Design in HTML and TailwindCSS
- [ ]  Create pull Request

**Comment by saad796** [comment]
I will work on issue#23 ,I will make a pricing section component which will be responsive to screen size.

**Comment by syedtalaljilani** [comment]
Well, I am assigning this issue to you. Follow the steps first to create a design in Figma

**Comment by saad796** [comment]
I have created a design for pricing section component.here is the figma link 

https://www.figma.com/file/KW6yosRz9Hd2HsNUZ9KvLe/Water-Ui?type=design&node-id=1-3&mode=design&t=Y4TVQcNa6m6RVEfo-0

**Comment by syedtalaljilani** [comment]
@saad796 great work! Now converts the design into code using HTML and Tailwindcss
